services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: atlus-discord-bot
    env_file:
      - .env 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: atlusdata
      POSTGRES_HOST: db  # This should match the service name of the database container
      POSTGRES_PORT: 5432
    depends_on:
      - db
    volumes: 
      - ./:/app

  db:
    image: postgres:13  # Or whichever version of PostgreSQL you prefer
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=atlusdata
    ports:
      - "5433:5432"  # 2nd port -> host container 
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./data:/data  # ✅ Ensure data is mounted correctly
      - ./pgdata:/var/lib/postgresql/data  # Persist actual database files
    restart: unless-stopped  # Auto-restart the database if it crashes

volumes:
  postgres_data:  # Named volume for persisting PostgreSQL data